version: '3'

services:
  api:
    build: .
    image: ucl-assistant-api
    env_file: .env
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '127.0.0.1:6379:6379'
