const WORKSPACE_PATH = `/workspaces`
const PEOPLE_PATH = `/people`
const ROOMS_PATH = `/rooms`
const TIMETABLE_PATH = `/timetable`
module.exports = {
  TIMETABLE_PERSONAL_PATH: `${TIMETABLE_PATH}/personal`,
  TIMETABLE_MODULE_PATH: `${TIMETABLE_PATH}/module`,
  WORKSPACE_SURVEYS_PATH: `${WORKSPACE_PATH}/surveys`,
  WORKSPACE_SUMMARY_PATH: `${WORKSPACE_PATH}/summary`,
  WORKSPACE_HISTORIC_DATA_PATH: `${WORKSPACE_PATH}/historic`,
  WORKSPACE_EQUIPMENT_PATH: `${WORKSPACE_PATH}/equipment`,
  PEOPLE_SEARCH_PATH: `${PEOPLE_PATH}/search`,
  ROOMS_SEARCH_PATH: `${ROOMS_PATH}/rooms`,
}
